stapsh: convert dbug macros to void statements
This is to get around a clang warning:

   CC     stapsh-stapsh.o
 ../../../runtime/staprun/stapsh.c:241:3: error: expression result
     unused [-Werror,-Wunused-value]
   vdbug (1, format, dbug_args);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ../../../runtime/staprun/stapsh.c:100:58: note: instantiated from:
 #define vdbug(level, format, args) ( (verbose < level) ? 0 : \
                                                          ^

None of the dbug/vdbug callers care about the fprintf return values,
so just squash them and move on.