Synchronize class/struct declarations
We are not very consistent about choosing struct vs class types, and in
some cases we have a mismatch between declaration and definition of a
given type.  Gcc doesn't care, but clang -Wall complains:

  CXX    stap-main.o
In file included from ../main.cxx:12:
../staptree.h:489:1: error: struct 'vardecl' was previously declared
        as a class [-Werror,-Wmismatched-tags]
struct vardecl: public symboldecl
^~~~~~
class
../staptree.h:218:7: note: previous use is here
class vardecl;
      ^

In all cases, I left the definition alone, and adjusted the declaration
to match, so it should be semantically unchanged.