Tell the user if UTS_VERSION does not match running kernel
The test is done before looking at build-id since build-id error
messages like

ERROR: Build-id mismatch: "kernel" vs. "vmlinux-2.6.32-5-amd64" byte 0 (0x5e vs 0xff)
Pass 5: run failed.  Try again with another '--vp 00001' option.

are not very user-friendly.